import type { Metadata } from "next";
import { Barlow_Semi_Condensed } from "next/font/google";
import "./globals.css";
import GameContextProvider from "@/contexts/GameContextProvider";

const barlow = Barlow_Semi_Condensed({
  subsets: ["latin"],
  weight: ["600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${barlow.className} from-radialFirst to-radialSecond min-h-screen bg-gradient-to-b bg-cover bg-no-repeat`}
      >
        <GameContextProvider>{children}</GameContextProvider>
      </body>
    </html>
  );
}
